jd_php_project_analyzer_homepage:
    path:     /{_locale}/ppa
    defaults: { _controller: JDPhpProjectAnalyzerBundle:Main:index }
    requirements:
        _locale: en|fr

jd_php_project_analyzer_phpinfo:
    path:     /ppa/phpinfo
    defaults: { _controller: JDPhpProjectAnalyzerBundle:Main:phpinfo }

jd_php_project_analyzer_analyze:
    path:     /ppa/analyze
    defaults: { _controller: JDPhpProjectAnalyzerBundle:Main:analyze }
