services:
    jd_ppa.projectAnalyzer:
        class: JD\PhpProjectAnalyzerBundle\Manager\ProjectAnalyzer
        arguments: [%jd.ppa.global%, "@translator", %kernel.root_dir%/../]
    
    jd_ppa.scriptManager:
        class: JD\PhpProjectAnalyzerBundle\Manager\ScriptManager
        arguments: [%jd.ppa.global%, %kernel.root_dir%/../]
