language: php

php:
    - 5.4
    - 5.5
    - 5.6
    
matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    
before_install:
    - wget http://getcomposer.org/composer.phar    
    
before_script:
    - php composer.phar install --dev
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash

script: 
    - phpunit -c phpunit.xml
    - phpcs --standard=PSR2 --extensions=php Entities Manager Command Controller DependencyInjection Traits

notifications:
  email:
    - jd.labails@gmail.com
