language: php

php:
    - 5.5
    - 5.6
    - 7
    
before_install:
    - wget http://getcomposer.org/composer.phar    
    
before_script:
    - php composer.phar install --dev
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash

script: 
    - phpunit -c phpunit.xml
    - phpcs --standard=PSR2 --extensions=php Entities Manager Command Controller DependencyInjection Traits

notifications:
  email:
    - jd.labails@gmail.com
