language: php

php:
    - 5.6
    - 7.0
    
matrix:
  include:
    - php: 5.6
      env:
        - COVERALLS=1
        - PHPCS=1
    
before_install:
    - wget http://getcomposer.org/composer.phar    

before_script:
    - php composer.phar install --dev
#    - pyrus install pear/PHP_CodeSniffer
#    - phpenv rehash

script:
    - ls -la vendor
    - ls -la vendor/bin
    - bin/simple-phpunit -c phpunit.xml
    - bin/phpcs --standard=PSR2 --extensions=php Entities Manager Command Controller DependencyInjection Traits

notifications:
  email:
    - jd.labails@gmail.com
